@extends('admin.layouts.app')

@section('title', 'Detail Biaya Pembesaran - ' . $pembesaran->batch_produksi_id)

@php
	$breadcrumbs = [
		['label' => 'Backoffice', 'link' => route('admin.dashboard')],
		['label' => 'Pembesaran', 'link' => route('admin.pembesaran')],
		['label' => 'Detail Batch', 'link' => route('admin.pembesaran.show', $pembesaran->id), 'badge' => $pembesaran->batch_produksi_id],
		['label' => 'Detail Biaya'],
	];
@endphp

@push('styles')
<style>
	/* Receipt (Struk) style */
	.struk-card {
		max-width: 420px;
		max-height: 90vh;
		padding: 1rem 1.25rem;
		border: 1px dashed #444;
		background: #fff;
		font-family: 'Courier New', monospace;
		color: #111;
		box-shadow: 0 6px 18px rgba(0,0,0,0.05);
		position: fixed;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		overflow-y: auto;
	}
	.struk-header { text-align: center; margin-bottom: 0.5rem; }
	.struk-header h3 { margin: 0; font-size: 1.05rem; letter-spacing: 1px; }
	.struk-meta { text-align: center; font-size: 0.8rem; color:#333; margin-bottom: .75rem }
	.struk-items { width:100%; border-top:1px dashed #ddd; border-bottom:1px dashed #ddd; padding: .5rem 0; margin-bottom:.5rem }
	.struk-items .row { font-size:0.85rem; padding: .25rem 0 }
	.struk-items .label { text-align:left }
	.struk-items .value { text-align:right }
	.struk-total { display:flex; justify-content:space-between; font-weight:700; font-size:1rem; padding-top:.5rem }
	.struk-note { font-size:0.75rem; color:#666; margin-top:.75rem; }
	.struk-footer { text-align:center; margin-top:1rem; font-size:0.85rem }
	.small-muted { font-size: 0.75rem; color: #666 }
</style>
@endpush

@section('content')
<div class="container">
	<div class="struk-card">
		<div class="struk-header">
			<h3>VIGAZA FARM</h3>
			<div class="small-muted">Gudang & Pembesaran</div>
		</div>

		<div class="struk-meta">
			<div>Batch: <strong>{{ $pembesaran->batch_produksi_id }}</strong></div>
			<div>{{ $pembesaran->kandang->nama_kandang ?? '-' }} • Umur: {{ (int)$umurHari }} hari</div>
			<div>Tanggal: {{ \Carbon\Carbon::now()->format('d/m/Y H:i') }}</div>
		</div>

		<div class="struk-items">
			<div class="row">
				<div class="col-7 label">Total Konsumsi Pakan</div>
				<div class="col-5 value">{{ number_format($totalPakan,2,',','.') }} kg</div>
			</div>
			<div class="row">
				<div class="col-7 label">Total Biaya Pakan</div>
				<div class="col-5 value">Rp {{ number_format($totalBiayaPakan,0,',','.') }}</div>
			</div>
			<div class="row">
				<div class="col-7 label">Biaya Kesehatan & Vaksinasi</div>
				<div class="col-5 value">Rp {{ number_format($totalBiayaKesehatan ?? 0,0,',','.') }}</div>
			</div>
		</div>

		@php $grand = ($totalBiayaPakan ?? 0) + ($totalBiayaKesehatan ?? 0); @endphp
		<div class="struk-total">
			<div>Total</div>
			<div>Rp {{ number_format($grand,0,',','.') }}</div>
		</div>

		<div class="struk-items" style="margin-top: .65rem;">
			<div class="row">
				<div class="col-7 label">Populasi Saat Ini</div>
				<div class="col-5 value">{{ number_format($populasiSaatIni) }} ekor</div>
			</div>
			<div class="row">
				<div class="col-7 label">Biaya per Ekor</div>
				<div class="col-5 value">Rp {{ $populasiSaatIni > 0 ? number_format(round($grand / $populasiSaatIni),0,',','.') : '0' }}</div>
			</div>
		</div>

		<div class="struk-note">Catatan: Data diperbarui realtime dari pencatatan harian. Simpan struk ini untuk referensi biaya.</div>

		<div class="struk-footer">
			<div>Terima kasih</div>
			<div class="small-muted">Generated by Vigaza Farm</div>
		</div>
	</div>
</div>

@endsection

